# Generated by Django 4.2.8 on 2023-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='listing',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
