# Generated by Django 4.2.8 on 2023-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_time_listing_end_time_listing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='map_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
