# Generated by Django 4.2.8 on 2023-12-17 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
