# Generated by Django 5.0 on 2024-01-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towns', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='town',
            field=models.CharField(default='Cheptulu', max_length=255),
        ),
    ]
