# Generated by Django 5.0 on 2024-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_town_listing_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='town',
            field=models.CharField(max_length=255),
        ),
    ]
