# Generated by Django 4.2.8 on 2023-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='specific',
            field=models.CharField(default='listing_type', max_length=255),
        ),
    ]
