# Generated by Django 4.2.8 on 2023-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_specific'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=255)),
            ],
        ),
    ]
