# Generated by Django 5.0 on 2024-01-31 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_town'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(related_name='listing_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
