# Generated by Django 4.2.8 on 2023-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_specific'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Specific',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='specific',
            new_name='category',
        ),
    ]
