# Generated by Django 5.0.1 on 2024-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='snippet',
            field=models.CharField(default='Click link above to know more about the business!!!', max_length=255),
        ),
    ]
