# Generated by Django 4.2.8 on 2023-12-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_category_delete_specific_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCounties', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towns', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wards', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='sub_county',
            field=models.CharField(default='Hamisi', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='town',
            field=models.CharField(default='Cheptulu', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='ward',
            field=models.CharField(default='Kaimosi', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Organization', max_length=255),
        ),
    ]
