# Generated by Django 5.0.1 on 2024-02-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_userprofile_facebook_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pinterest_url',
            new_name='tiktok_url',
        ),
    ]
